import type { Metadata } from "next";
import "./globals.css";
import Topbar from "@/components/topbar/topbar";
import Sidebar from "@/components/sidebar/sidebar";

export const metadata: Metadata = {
   title: "scoial media",
   description: "Generated by sanjay",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`antialiased`}>
             <Topbar />
            <div className=" flex w-full">
               <div className="fixed hidden md:block w-[20vw] min-h-[100vh] ">
                  <Sidebar />
               </div>
               <div className="relative w-full  md:w-[80vw] md:left-[20vw]">
                  {children}
               </div>
            </div>
         </body>
      </html>
   );
}
